"""scripts/build_ai_index.py -- regenerate AI_INDEX.md from the current codebase.

Boss directive 2026-05-08: codebase has 62+ commits, AI agents waste tokens
re-discovering the structure each session. Build a single index file with:
1. Where-to-put-new-code decision tree
2. Feature catalog (F00-F45 -> files/tables/crons)
3. Module catalog (src/stock/*.py exports + tests)
4. Data catalog (data/*.yaml + first-line docstring)
5. DB schema (CREATE TABLE list)
6. Cron catalog (UTC time -> job_id -> handler)
7. CLI catalog (stock <cmd> -> handler -> brief)

Pure Python AST + regex. No LLM cost. Re-run anytime via:
  python scripts/build_ai_index.py
"""
from __future__ import annotations

import ast
import io
import re
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_ast(path: Path) -> ast.Module | None:
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return None


def _module_top_level(tree: ast.Module) -> tuple[list[str], list[str], str | None]:
    """Return (exported_names, imported_modules, docstring) for a module."""
    exports: list[str] = []
    imports: set[str] = set()
    doc = ast.get_docstring(tree)
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if not node.name.startswith("_"):
                exports.append(node.name)
        elif isinstance(node, ast.Import):
            for n in node.names:
                imports.add(n.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            mod = (node.module or "").split(".")[0]
            if mod:
                imports.add(mod)
    return exports, sorted(imports), doc


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def section_intro() -> str:
    return (
        "# AI_INDEX -- machine-readable codebase index\n"
        "\n"
        "_Auto-generated by `scripts/build_ai_index.py`. Re-run after significant "
        "changes. **AI agents: read this FIRST when starting a session** -- it "
        "saves 5-10 file reads worth of tokens before you can find where to edit._\n"
        "\n"
        "Source of truth pointers (when this index is stale):\n"
        "- `code_structure.md` -- living long-form structure doc\n"
        "- `WORKFLOW.md` -- runtime/operational view\n"
        "- `docs/feature_backlog.md` -- canonical feature ledger F00-F45\n"
        "- `CLAUDE.md` -- coding style + conventions\n"
        "\n---\n\n"
    )


def section_decision_tree() -> str:
    return (
        "## 1. Where to put new code (decision tree)\n"
        "\n"
        "| If you are adding... | Edit / create |\n"
        "| --- | --- |\n"
        "| **A new feature (F46+)** | (a) entry in `docs/feature_backlog.md` ABOVE the backfill section with TODO+plan, (b) new module `src/stock/<name>.py` + test `tests/test_<name>.py` |\n"
        "| **A new cron job** | `src/stock/orchestrator.py` -- find `create_scheduler()` near line 990; add `scheduler.add_job(...)`; bump test count in `tests/test_orchestrator.py` |\n"
        "| **A new CLI command** | `src/stock/cli.py` -- find an existing `@app.command(...)` block, add yours nearby |\n"
        "| **A new SQLite table** | `src/stock/db.py` -- append to `_SCHEMA_SQL` block; existing-DB schema migrations not yet wired (delete `data/stock.db` to re-init in dev) |\n"
        "| **A new data YAML** | `data/<name>.yaml` + add a row to AI_INDEX section 4 + reference from the consuming module |\n"
        "| **A new prompt template** | `prompts/<name>.txt` (feature_backlog, research, etc.) + reference from `_load_*_prompt()` |\n"
        "| **A new Claude Code skill** | `~/.claude/commands/<name>.md` with YAML frontmatter `description:` + body |\n"
        "| **A new pydantic model** | inline in the module that owns it (one model per concern) |\n"
        "| **A new LLM-touching helper** | route through `stock.models.get_core_client()` (NEVER `get_client('minimax')` directly except in fallback paths) |\n"
        "| **A new test fixture** | `tests/conftest.py` if shared, else inline in the test file |\n"
        "| **A new background script** | `scripts/<name>.py` -- self-contained, run via `python scripts/<name>.py` |\n"
        "\n---\n\n"
    )


def section_features() -> str:
    out = ["## 2. Feature catalog (from docs/feature_backlog.md)\n\n"]
    backlog_path = ROOT / "docs" / "feature_backlog.md"
    if not backlog_path.exists():
        return out[0] + "_(feature_backlog.md missing)_\n\n---\n\n"
    text = backlog_path.read_text(encoding="utf-8")
    out.append("| Feature | Description | Status |\n| --- | --- | --- |\n")
    feat_re = re.compile(
        r"## (F\d+(?:-F?\d+)?)\s*[-—]+\s*([^\n]+)\n.*?\*\*Status\*\*:\s*([^\n]+)",
        re.DOTALL,
    )
    for m in feat_re.finditer(text):
        feat = m.group(1).strip()
        desc = m.group(2).strip()
        status = m.group(3).strip()[:60]
        # Clean common formatting
        desc_clean = desc.replace("|", "/").strip()[:80]
        out.append(f"| {feat} | {desc_clean} | {status} |\n")
    out.append("\n---\n\n")
    return "".join(out)


def section_modules() -> str:
    out = ["## 3. Module catalog (src/stock/*.py)\n\n"]
    out.append("Auto-extracted from AST. Only top-level (non-`_`-prefix) names listed.\n\n")
    out.append("| Module | Purpose (first line of docstring) | Top-level exports |\n| --- | --- | --- |\n")
    src_dir = ROOT / "src" / "stock"
    if not src_dir.exists():
        return out[0] + "_(src/stock missing)_\n\n---\n\n"
    for path in sorted(src_dir.glob("**/*.py")):
        if path.name == "__init__.py":
            continue
        rel = path.relative_to(ROOT).as_posix()
        tree = _parse_ast(path)
        if tree is None:
            continue
        exports, _imports, doc = _module_top_level(tree)
        purpose = ((doc or "").splitlines() or ["(no docstring)"])[0][:80].replace("|", "/")
        ex_str = ", ".join(exports[:8])
        if len(exports) > 8:
            ex_str += f" ... +{len(exports)-8}"
        out.append(f"| `{rel}` | {purpose} | {ex_str or '_(no exports)_'} |\n")
    out.append("\n---\n\n")
    return "".join(out)


def section_data() -> str:
    out = ["## 4. Data catalog (data/*.yaml)\n\n"]
    data_dir = ROOT / "data"
    if not data_dir.exists():
        return out[0] + "_(data/ missing)_\n\n---\n\n"
    out.append("| File | First comment line / purpose |\n| --- | --- |\n")
    for path in sorted(data_dir.glob("*.yaml")):
        rel = path.relative_to(ROOT).as_posix()
        try:
            first_lines = path.read_text(encoding="utf-8").splitlines()[:3]
        except OSError:
            first_lines = []
        purpose = "_(empty)_"
        for line in first_lines:
            stripped = line.strip().lstrip("#").strip()
            if stripped and not stripped.startswith("---"):
                purpose = stripped[:90].replace("|", "/")
                break
        out.append(f"| `{rel}` | {purpose} |\n")
    out.append("\n---\n\n")
    return "".join(out)


def section_db_schema() -> str:
    out = ["## 5. DB schema (CREATE TABLE list)\n\n"]
    db_path = ROOT / "src" / "stock" / "db.py"
    if not db_path.exists():
        return out[0] + "_(db.py missing)_\n\n---\n\n"
    text = db_path.read_text(encoding="utf-8")
    table_re = re.compile(r"CREATE TABLE IF NOT EXISTS\s+(\w+)\s*\(", re.IGNORECASE)
    tables = sorted(set(table_re.findall(text)))
    out.append("Tables defined in `src/stock/db.py` `_SCHEMA_SQL`:\n\n")
    for t in tables:
        out.append(f"- `{t}`\n")
    out.append(f"\n_Total: **{len(tables)} tables**._\n\n---\n\n")
    return "".join(out)


def section_cron() -> str:
    out = ["## 6. Cron catalog (orchestrator.add_job blocks)\n\n"]
    orch_path = ROOT / "src" / "stock" / "orchestrator.py"
    if not orch_path.exists():
        return out[0] + "_(orchestrator.py missing)_\n\n---\n\n"
    text = orch_path.read_text(encoding="utf-8")
    # Find each scheduler.add_job(...) block + its handler + id
    add_job_re = re.compile(
        r"scheduler\.add_job\(\s*(\w+)\s*,\s*CronTrigger\(([^)]+)\)\s*,\s*id=\"([^\"]+)\"",
        re.DOTALL,
    )
    jobs = []
    for m in add_job_re.finditer(text):
        handler = m.group(1)
        trigger_args = " ".join(m.group(2).split())[:80]
        job_id = m.group(3)
        jobs.append((job_id, handler, trigger_args))
    out.append(f"_Total: **{len(jobs)} jobs registered**_\n\n")
    out.append("| Job ID | Handler | Trigger |\n| --- | --- | --- |\n")
    for job_id, handler, trigger in jobs:
        out.append(f"| `{job_id}` | `{handler}` | `{trigger}` |\n")
    out.append("\n---\n\n")
    return "".join(out)


def section_cli() -> str:
    out = ["## 7. CLI catalog (stock <cmd>)\n\n"]
    cli_path = ROOT / "src" / "stock" / "cli.py"
    if not cli_path.exists():
        return out[0] + "_(cli.py missing)_\n\n---\n\n"
    text = cli_path.read_text(encoding="utf-8")
    # Match @app.command("name") followed by def func_name(...) -> None: """docstring"""
    cmd_re = re.compile(
        r'@(?:app|trend_app|conviction_app|holding_app|queue_app)\.command\("([^"]+)"\)\s*\n'
        r'def\s+\w+\([^)]*\)\s*->[^:]+:\s*\n\s*"""([^"\n]+)"',
        re.DOTALL,
    )
    cmds = sorted({(m.group(1), m.group(2).strip()[:90].replace("|", "/")) for m in cmd_re.finditer(text)})
    out.append(f"_Total: **{len(cmds)} commands**_\n\n")
    out.append("| Command | Description |\n| --- | --- |\n")
    for name, desc in cmds:
        out.append(f"| `stock {name}` | {desc} |\n")
    out.append("\n---\n\n")
    return "".join(out)


def section_recent_changes() -> str:
    """List the 10 most recently modified files (mtime) for quick orientation."""
    out = ["## 8. Recently modified (last 10 files)\n\n"]
    out.append("Most-recently-edited files in tracked dirs. Useful for picking up where the last session left off.\n\n")
    candidates: list[Path] = []
    for sub in ("src/stock", "tests", "data", "prompts", "docs", "scripts"):
        d = ROOT / sub
        if d.exists():
            candidates.extend(p for p in d.glob("**/*") if p.is_file() and not any(
                part.startswith(".") or part == "__pycache__" for part in p.parts
            ))
    by_mtime = sorted(candidates, key=lambda p: p.stat().st_mtime, reverse=True)[:10]
    out.append("| File | Modified |\n| --- | --- |\n")
    from datetime import datetime
    for p in by_mtime:
        rel = p.relative_to(ROOT).as_posix()
        mt = datetime.fromtimestamp(p.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
        out.append(f"| `{rel}` | {mt} |\n")
    out.append("\n---\n\n")
    return "".join(out)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    sections = [
        section_intro(),
        section_decision_tree(),
        section_features(),
        section_modules(),
        section_data(),
        section_db_schema(),
        section_cron(),
        section_cli(),
        section_recent_changes(),
    ]
    out_path = ROOT / "AI_INDEX.md"
    body = "".join(sections)
    body += (
        "_End of index. Re-generate via `python scripts/build_ai_index.py`._\n"
    )
    out_path.write_text(body, encoding="utf-8")
    print(f"Wrote {out_path} ({len(body):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
